----------------- Execute Function  ---------------

function ExecuteFunction()
-- Erkennt welcher Befehl bearbeitet werden soll oder gibt ansonsten einen Fehler aus.

	local valueDevelopt
	
	if     BefehlString == "Contrast+" 			then ChangeAdjustPanel("Contrast","positiv")
    elseif BefehlString == "Temp+" 				then ChangeAdjustPanel("Temperature","positiv")
    elseif BefehlString == "Tint+" 				then ChangeAdjustPanel("Tint","positiv")	                            
	elseif BefehlString == "Shadows+" 			then ChangeAdjustPanel("Shadows","positiv")        
	elseif BefehlString == "Whites+" 			then ChangeAdjustPanel("Whites","positiv")        
	elseif BefehlString == "Blacks+" 			then ChangeAdjustPanel("Blacks","positiv")        
	elseif BefehlString == "Highlights+" 		then ChangeAdjustPanel("Highlights","positiv")        
	elseif BefehlString == "Exposure+" 			then ChangeExposure("Exposure","positiv")        
	elseif BefehlString == "Clarity+" 			then ChangeAdjustPanel("Clarity","positiv")        
	elseif BefehlString == "Vibrance+" 			then ChangeAdjustPanel("Vibrance","positiv")        
	elseif BefehlString == "Saturation+" 		then ChangeAdjustPanel("Saturation","positiv")        			
	elseif BefehlString == "HueRed+" 			then ChangeAdjustPanel("HueAdjustmentRed","positiv")        
	elseif BefehlString == "SatRed+" 			then ChangeAdjustPanel("SaturationAdjustmentRed","positiv")        
	elseif BefehlString == "LumRed+" 			then ChangeAdjustPanel("LuminanceAdjustmentRed","positiv")        
	elseif BefehlString == "HueOrange+" 		then ChangeAdjustPanel("HueAdjustmentOrange","positiv")        
	elseif BefehlString == "SatOrange+" 		then ChangeAdjustPanel("SaturationAdjustmentOrange","positiv")        
	elseif BefehlString == "LumOrange+" 		then ChangeAdjustPanel("LuminanceAdjustmentOrange","positiv")        
	elseif BefehlString == "HueYellow+" 		then ChangeAdjustPanel("HueAdjustmentYellow","positiv")        
	elseif BefehlString == "SatYellow+" 		then ChangeAdjustPanel("SaturationAdjustmentYellow","positiv")
	elseif BefehlString == "LumYellow+" 		then ChangeAdjustPanel("LuminanceAdjustmentYellow","positiv")
	elseif BefehlString == "HueGreen+" 			then ChangeAdjustPanel("HueAdjustmentGreen","positiv")
	elseif BefehlString == "SatGreen+" 			then ChangeAdjustPanel("SaturationAdjustmentGreen","positiv")
	elseif BefehlString == "LumGreen+" 			then ChangeAdjustPanel("LuminanceAdjustmentGreen","positiv")
	elseif BefehlString == "HueAqua+" 			then ChangeAdjustPanel("HueAdjustmentAqua","positiv")
	elseif BefehlString == "SatAqua+"			then ChangeAdjustPanel("SaturationAdjustmentAqua","positiv")
	elseif BefehlString == "LumAqua+" 			then ChangeAdjustPanel("LuminanceAdjustmentAqua","positiv")
	elseif BefehlString == "HueBlue+" 			then ChangeAdjustPanel("HueAdjustmentBlue","positiv")
	elseif BefehlString == "SatBlue+"			then ChangeAdjustPanel("SaturationAdjustmentBlue","positiv")
	elseif BefehlString == "LumBlue+" 			then ChangeAdjustPanel("LuminanceAdjustmentBlue","positiv")
	elseif BefehlString == "HuePurple+" 		then ChangeAdjustPanel("HueAdjustmentPurple","positiv")
	elseif BefehlString == "SatPurple+" 		then ChangeAdjustPanel("SaturationAdjustmentPurple","positiv")        
	elseif BefehlString == "LumPurple+" 		then ChangeAdjustPanel("LuminanceAdjustmentPurple","positiv")
	elseif BefehlString == "HueMagenta+" 		then ChangeAdjustPanel("HueAdjustmentMagenta","positiv")
	elseif BefehlString == "SatMagenta+" 		then ChangeAdjustPanel("SaturationAdjustmentMagenta","positiv")
	elseif BefehlString == "LumMagenta+" 		then ChangeAdjustPanel("LuminanceAdjustmentMagenta","positiv")
	elseif BefehlString == "Crop+" 				then ChangeAdjustPanel("straightenAngle","positiv")
	elseif BefehlString == "Vignet+" 			then ChangeAdjustPanel("PostCropVignetteAmount","positiv")
	
	elseif BefehlString == "Contrast-" 			then ChangeAdjustPanel("Contrast","negativ")
    elseif BefehlString == "Temp-" 				then ChangeAdjustPanel("Temperature","negativ")
    elseif BefehlString == "Tint-" 				then ChangeAdjustPanel("Tint","negativ")	        
	elseif BefehlString == "Shadows-" 			then ChangeAdjustPanel("Shadows","negativ")        
	elseif BefehlString == "Blacks-" 			then ChangeAdjustPanel("Blacks","negativ")        
	elseif BefehlString == "Whites-" 			then ChangeAdjustPanel("Whites","negativ")        
	elseif BefehlString == "Highligths-" 		then ChangeAdjustPanel("Highlights","negativ")        
	elseif BefehlString == "Exposure-" 			then ChangeExposure("Exposure","negativ")        
	elseif BefehlString == "Clarity-" 			then ChangeAdjustPanel("Clarity","negativ")        
	elseif BefehlString == "Vibrance-" 			then ChangeAdjustPanel("Vibrance","negativ")        
	elseif BefehlString == "Saturation-" 		then ChangeAdjustPanel("Saturation","negativ")        
	elseif BefehlString == "HueRed-" 			then ChangeAdjustPanel("HueAdjustmentRed","negativ")        
	elseif BefehlString == "SatRed-" 			then ChangeAdjustPanel("SaturationAdjustmentRed","negativ")        
	elseif BefehlString == "LumRed-" 			then ChangeAdjustPanel("LuminanceAdjustmentRed","negativ")        
	elseif BefehlString == "HueOrange-" 		then ChangeAdjustPanel("HueAdjustmentOrange","negativ")        
	elseif BefehlString == "SatOrange-" 		then ChangeAdjustPanel("SaturationAdjustmentOrange","negativ")        
	elseif BefehlString == "LumOrange-" 		then ChangeAdjustPanel("LuminanceAdjustmentOrange","negativ")        
	elseif BefehlString == "HueYellow-" 		then ChangeAdjustPanel("HueAdjustmentYellow","negativ")        
	elseif BefehlString == "SatYellow-" 		then ChangeAdjustPanel("SaturationAdjustmentYellow","negativ")
	elseif BefehlString == "LumYellow-" 		then ChangeAdjustPanel("LuminanceAdjustmentYellow","negativ")
	elseif BefehlString == "HueGreen-" 			then ChangeAdjustPanel("HueAdjustmentGreen","negativ")
	elseif BefehlString == "SatGreen-" 			then ChangeAdjustPanel("SaturationAdjustmentGreen","negativ")
	elseif BefehlString == "LumGreen-" 			then ChangeAdjustPanel("LuminanceAdjustmentGreen","negativ")
	elseif BefehlString == "HueAqua-" 			then ChangeAdjustPanel("HueAdjustmentAqua","negativ")
	elseif BefehlString == "SatAqua-"		 	then ChangeAdjustPanel("SaturationAdjustmentAqua","negativ")
	elseif BefehlString == "LumAqua-" 			then ChangeAdjustPanel("LuminanceAdjustmentAqua","negativ")
	elseif BefehlString == "HueBlue-" 			then ChangeAdjustPanel("HueAdjustmentBlue","negativ")
	elseif BefehlString == "SatBlue-" 			then ChangeAdjustPanel("SaturationAdjustmentBlue","negativ")
	elseif BefehlString == "LumBlue-" 			then ChangeAdjustPanel("LuminanceAdjustmentBlue","negativ")
	elseif BefehlString == "HuePurple-"			then ChangeAdjustPanel("HueAdjustmentPurple","negativ")
	elseif BefehlString == "SatPurple-" 		then ChangeAdjustPanel("SaturationAdjustmentPurple","negativ")        
	elseif BefehlString == "LumPurple-" 		then ChangeAdjustPanel("LuminanceAdjustmentPurple","negativ")
	elseif BefehlString == "HueMagenta-" 		then ChangeAdjustPanel("HueAdjustmentMagenta","negativ")
	elseif BefehlString == "SatMagenta-" 		then ChangeAdjustPanel("SaturationAdjustmentMagenta","negativ")
	elseif BefehlString == "LumMagenta-" 		then ChangeAdjustPanel("LuminanceAdjustmentMagenta","negativ")
	elseif BefehlString == "Crop-" 				then ChangeAdjustPanel("straightenAngle","negativ")
	elseif BefehlString == "Vignet-" 			then ChangeAdjustPanel("PostCropVignetteAmount","negativ")
	
	elseif BefehlString == "Contrast0" 			then ChangeAdjustPanel("Contrast","zero")
    elseif BefehlString == "Temp0" 				then ChangeAdjustPanel("Temperature","zero")
    elseif BefehlString == "Tint0" 				then ChangeAdjustPanel("Tint","zero")
	elseif BefehlString == "Shadows0" 			then ChangeAdjustPanel("Shadows","zero")        
	elseif BefehlString == "Blacks0" 			then ChangeAdjustPanel("Blacks","zero")        
	elseif BefehlString == "Whites0" 			then ChangeAdjustPanel("Whites","zero")        
	elseif BefehlString == "Highligths0" 		then ChangeAdjustPanel("Highlights","zero")        
	elseif BefehlString == "Exposure0" 			then ChangeExposure("Exposure","zero")        
	elseif BefehlString == "Clarity0" 			then ChangeAdjustPanel("Clarity","zero")        
	elseif BefehlString == "Vibrance0" 			then ChangeAdjustPanel("Vibrance","zero")        
	elseif BefehlString == "Saturation0" 		then ChangeAdjustPanel("Saturation","zero")        
	elseif BefehlString == "HueRed0" 			then ChangeAdjustPanel("HueAdjustmentRed","zero")        
	elseif BefehlString == "SatRed0" 			then ChangeAdjustPanel("SaturationAdjustmentRed","zero")        
	elseif BefehlString == "LumRed0" 			then ChangeAdjustPanel("LuminanceAdjustmentRed","zero")        
	elseif BefehlString == "HueOrange0" 		then ChangeAdjustPanel("HueAdjustmentOrange","zero")        
	elseif BefehlString == "SatOrange0" 		then ChangeAdjustPanel("SaturationAdjustmentOrange","zero")        
	elseif BefehlString == "LumOrange0" 		then ChangeAdjustPanel("LuminanceAdjustmentOrange","zero")        
	elseif BefehlString == "HueYellow0" 		then ChangeAdjustPanel("HueAdjustmentYellow","zero")        
	elseif BefehlString == "SatYellow0" 		then ChangeAdjustPanel("SaturationAdjustmentYellow","zero")
	elseif BefehlString == "LumYellow0" 		then ChangeAdjustPanel("LuminanceAdjustmentYellow","zero")
	elseif BefehlString == "HueGreen0" 			then ChangeAdjustPanel("HueAdjustmentGreen","zero")
	elseif BefehlString == "SatGreen0"			then ChangeAdjustPanel("SaturationAdjustmentGreen","zero")
	elseif BefehlString == "LumGreen0" 			then ChangeAdjustPanel("LuminanceAdjustmentGreen","zero")
	elseif BefehlString == "HueAqua0" 			then ChangeAdjustPanel("HueAdjustmentAqua","zero")
	elseif BefehlString == "SatAqua0" 			then ChangeAdjustPanel("SaturationAdjustmentAqua","zero")
	elseif BefehlString == "LumAqua0" 			then ChangeAdjustPanel("LuminanceAdjustmentAqua","zero")
	elseif BefehlString == "HueBlue0"			then ChangeAdjustPanel("HueAdjustmentBlue","zero")
	elseif BefehlString == "SatBlue0" 			then ChangeAdjustPanel("SaturationAdjustmentBlue","zero")
	elseif BefehlString == "LumBlue0" 			then ChangeAdjustPanel("LuminanceAdjustmentBlue","zero")
	elseif BefehlString == "HuePurple0"			then ChangeAdjustPanel("HueAdjustmentPurple","zero")
	elseif BefehlString == "SatPurple0" 		then ChangeAdjustPanel("SaturationAdjustmentPurple","zero")        
	elseif BefehlString == "LumPurple0" 		then ChangeAdjustPanel("LuminanceAdjustmentPurple",	"zero")
	elseif BefehlString == "HueMagenta0" 		then ChangeAdjustPanel("HueAdjustmentMagenta","zero")
	elseif BefehlString == "SatMagenta0" 		then ChangeAdjustPanel("SaturationAdjustmentMagenta","zero")
	elseif BefehlString == "LumMagenta0" 		then ChangeAdjustPanel("LuminanceAdjustmentMagenta","zero")  
	elseif BefehlString == "Crop0" 				then LrDevelopController.resetCrop()
	elseif BefehlString == "Vignet0" 			then ChangeAdjustPanel("PostCropVignetteAmount","zero")

	elseif BefehlString == "Hue" 		then ChangeHue()  
	elseif BefehlString == "Sat" 		then ChangeSat()  
	elseif BefehlString == "Lum" 		then ChangeLum()

	elseif BefehlString == "Rate0" 		then Rate(0);  
	elseif BefehlString == "Rate1" 		then Rate(1);  
	elseif BefehlString == "Rate2" 		then Rate(2);  
	elseif BefehlString == "Rate3" 		then Rate(3); 
	elseif BefehlString == "Rate4" 		then Rate(4);
	elseif BefehlString == "Rate5" 		then Rate(5);
		
	elseif BefehlString == "Undo" 		then Redo("Undo")    
	elseif BefehlString == "Redo" 		then Redo("Redo") 
		
	elseif BefehlString == "Right"		then Right()
	elseif BefehlString == "Left"		then Left()
	elseif BefehlString == "Up"			then Up()
	elseif BefehlString == "Down"		then Down()

	elseif BefehlString == "BW" 		then BlackWhite()
	elseif BefehlString == "Copy" 		then Copy()
	elseif BefehlString == "Paste" 		then Paste()
	elseif BefehlString == "Pick"		then Pick()
	elseif BefehlString == "Zoom"		then Zoom()
	elseif BefehlString == "Full"		then switchToFullscreen()
	elseif BefehlString == "Bevor"		then BevorAfter()
	elseif BefehlString == "BevorReset"	then BevorAfterReset()

	elseif BefehlString == "Grid" 		then ChangeModule("library")
	elseif BefehlString == "Devel"		then ChangeModule("develop")

	elseif BefehlString == "Verb"		then StartAsync();
    elseif BefehlString == "Kill"		then EndAsync();
        
    elseif BefehlString == "Driver"		then StartDriver();

	else LrDialogs.message( "Befehl wurde nicht erkannt", TestString, "info" )
	end
end

----------------- Execute Function  --------------- 